image: docker

services:
  - docker:dnid
 
stages:
  - build
  - deploy

build:
  stage: build
  script:
    - docker build =t newrepo .
    
deploy:
  stage: deploy
  script:
    - docker run -d -p 80:80 newrepo test
